language: node_js
node_js:
  - 11
    
env:
 - IMAGE_NAME=835827978632.dkr.ecr.us-east-2.amazonaws.com/juice:1.0-$TRAVIS_BUILD_NUMBER
    
services:
  - docker
  
script:
  - echo 'Use Docker !'

after_success:
  - pip install --user awscli
  - eval $(aws ecr get-login --no-include-email --region us-east-2)
  - docker build -t juice .
  - docker tag juice:latest 835827978632.dkr.ecr.us-east-2.amazonaws.com/juice:latest
  - docker push 835827978632.dkr.ecr.us-east-2.amazonaws.com/juice:latest
  - aws cloudformation deploy --template-file ./ecs-task.yaml --stack-name ecs-deployment --region us-east-2 --parameter-override ImageName=$IMAGE_NAME
  - aws cloudformation update-stack --template-body file://./ecs-task.yaml --stack-name ecs-deployment --region us-east-2 --parameters "ParameterKey=ImageName,ParameterValue=$IMAGE_NAME"

addons:
  sonarcloud:
    organization: "exwarning-github" # the key of the org you chose at step #3
    token:
      secure: $SONAR_TOKEN # encrypted value of your token
script:
  # other script steps might be done before running the actual analysis
  - sonar-scanner
